# GitHub Actions Workflow with MATLAB Actions
#
# For a general overview of GitHub Actions, see
# https://docs.github.com/en/actions
#
# For using MathWorks products in GitHub Actions, see
# https://github.com/matlab-actions/overview
#
# For details about the syntax of this file, see
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Copyright 2021-2023 The MathWorks, Inc.

name: CI using MATLAB

on:
  push:
    branches: [ R2023a ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

  pull_request:
    branches: [ R2023a ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

jobs:

  job-build-project:
    runs-on: ubuntu-latest
    permissions:
      # required for sarif upload
      security-events: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023b

      - name: Run project checks, lint, and tests
        uses: matlab-actions/run-build@v1
        with:
          tasks: qualify

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results/issues.sarif
          category: matlab-analysis

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'results/test-results.xml'

      - name: Upload Test Report  
        uses: actions/upload-artifact@v2
        with:
          name:  Test Results
          path: results/test-results.pdf

      - uses: 5monkeys/cobertura-action@master
        with:
          path: results/coverage.xml

