# GitHub Actions Workflow with MATLAB Actions
#
# For a general overview of GitHub Actions, see
# https://docs.github.com/en/actions
#
# For using MathWorks products in GitHub Actions, see
# https://github.com/matlab-actions/overview
#
# For details about the syntax of this file, see
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Copyright 2021-2023 The MathWorks, Inc.

name: CI using MATLAB

on:
  workflow_dispatch:
jobs:

  job-generate-jupyter-files:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit jupyter 
      # notebooks to the repository
      contents: write


    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023b

      - name: Run project checks, lint, and tests
        uses: matlab-actions/run-build@v1
        with:
          tasks: jupyter

      - name: Commit jupyter notebooks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.ipynb'

